### ISSUE TITLE
!! Export does not include Security and Units

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#51]
I am trying to export stock account transactions so I can do some math on the data.
Is there an option to add to the export at least security name and units? Exporting all columns would be great too.

**Comment by clovett** [comment]
I added this, let me know if it works for you:
https://github.com/clovett/MyMoney.Net/commit/051fef1486237e4299c0e16f6c0625890d65592f

**Comment by andreva7** [comment]
I have an updated visual studio and code compiles and runs.
I just ran my binary, which loaded my data file and exited.
I saw this in the output window: and the ESPP index file has over 80 entries in it

'MyMoney.exe' (CLR v4.0.30319: MyMoney.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemCore\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemCore.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
System.Windows.Data Error: 40 : BindingExpression path error: 'Name' property not found on 'object' ''AccountSectionHeader' (HashCode=47633640)'. BindingExpression:Path=Name; DataItem='AccountSectionHeader' (HashCode=47633640); target element is 'ListBoxItem' (Name=''); target property is 'AutomationId' (type 'String')
Exception thrown: 'System.ServiceModel.Security.MessageSecurityException' in mscorlib.dll
BeginGetExchangeRate for CAD threw exception: The HTTP request was forbidden with client authentication scheme 'Anonymous'.
The thread 0x51d4 has exited with code 0 (0x0).
System.Windows.Data Error: 40 : BindingExpression path error: 'Name' property not found on 'object' ''AccountSectionHeader' (HashCode=32109884)'. BindingExpression:Path=Name; DataItem='AccountSectionHeader' (HashCode=32109884); target element is 'ListBoxItem' (Name=''); target property is 'AutomationId' (type 'String')
Filtered 48 items, found 0 matches in 0 ms
System.Windows.Data Error: 40 : BindingExpression path error: 'Name' property not found on 'object' ''AccountSectionHeader' (HashCode=38770251)'. BindingExpression:Path=Name; DataItem='AccountSectionHeader' (HashCode=38770251); target element is 'ListBoxItem' (Name=''); target property is 'AutomationId' (type 'String')
'MyMoney.exe' (CLR v4.0.30319: MyMoney.exe): Loaded 'Microsoft.GeneratedCode'.
Exception thrown: 'System.ArgumentNullException' in mscorlib.dll
Failed to load statement index 'C:\Users\andre\OneDrive\Documents\Finance\andreva.MyMoney.Statements\Andre Fidelity ESPP\index.xml'
System.ArgumentNullException: Value cannot be null.
Parameter name: path2
   at System.IO.Path.Combine(String path1, String path2)
   at Walkabout.Attachments.StatementManager.CheckFileHashes(StatementIndex index) in C:\Users\andre\source\repos\clovett\MyMoney.Net\Source\WPF\MyMoney\Attachments\StatementManager.cs:line 359
   at Walkabout.Attachments.StatementManager.LoadIndexFile(Account a) in C:\Users\andre\source\repos\clovett\MyMoney.Net\Source\WPF\MyMoney\Attachments\StatementManager.cs:line 387
Exception thrown: 'System.ArgumentNullException' in mscorlib.dll
Failed to load statement index 'C:\Users\andre\OneDrive\Documents\Finance\andreva.MyMoney.Statements\Andre Well Fargo IRA\index.xml'
System.ArgumentNullException: Value cannot be null.
Parameter name: path2
   at System.IO.Path.Combine(String path1, String path2)
   at Walkabout.Attachments.StatementManager.CheckFileHashes(StatementIndex index) in C:\Users\andre\source\repos\clovett\MyMoney.Net\Source\WPF\MyMoney\Attachments\StatementManager.cs:line 359
   at Walkabout.Attachments.StatementManager.LoadIndexFile(Account a) in C:\Users\andre\source\repos\clovett\MyMoney.Net\Source\WPF\MyMoney\Attachments\StatementManager.cs:line 387
The program '[21216] MyMoney.exe' has exited with code 0 (0x0).

**Comment by clovett** [comment]
Hmmm, that looks messy, I published this change in a new official version 2.0.0.9, please let me know if you have any better luck with that version, thanks.

**Comment by andreva7** [comment]
Export of a stock account looks good! thanks.

**Comment by andreva7** [comment]
In the index file, one of the entries only has the Data and statement balance, no filename or hash. The balance is correct for the date.
I manually coped the statement file in the directory and added the statement entry in the XML record, and the statement now shows up.
I did not add a hash.

I did this on two index files that had the same problem.

Now, when I run the code under VS, just starting mymoney and then closing it (doing no actions in the UI whatsoever), I get

System.Windows.Data Error: 40 : BindingExpression path error: 'Name' property not found on 'object' ''AccountSectionHeader' (HashCode=27655246)'. BindingExpression:Path=Name; DataItem='AccountSectionHeader' (HashCode=27655246); target element is 'ListBoxItem' (Name=''); target property is 'AutomationId' (type 'String')
Exception thrown: 'System.ServiceModel.Security.MessageSecurityException' in mscorlib.dll
BeginGetExchangeRate for CAD threw exception: The HTTP request was forbidden with client authentication scheme 'Anonymous'.
The thread 0x2c48 has exited with code 0 (0x0).
'MyMoney.exe' (CLR v4.0.30319: MyMoney.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\Accessibility\v4.0_4.0.0.0__b03f5f7f11d50a3a\Accessibility.dll'.
System.Windows.Data Error: 40 : BindingExpression path error: 'Name' property not found on 'object' ''AccountSectionHeader' (HashCode=2615989)'. BindingExpression:Path=Name; DataItem='AccountSectionHeader' (HashCode=2615989); target element is 'ListBoxItem' (Name=''); target property is 'AutomationId' (type 'String')
Filtered 36 items, found 0 matches in 0 ms
System.Windows.Data Error: 40 : BindingExpression path error: 'Name' property not found on 'object' ''AccountSectionHeader' (HashCode=35390522)'. BindingExpression:Path=Name; DataItem='AccountSectionHeader' (HashCode=35390522); target element is 'ListBoxItem' (Name=''); target property is 'AutomationId' (type 'String')
'MyMoney.exe' (CLR v4.0.30319: MyMoney.exe): Loaded 'Microsoft.GeneratedCode'.
Exception thrown: 'System.IO.IOException' in mscorlib.dll
Failed to load statement index 'C:\Users\andre\OneDrive\Documents\Finance\andreva.MyMoney.Statements\Andre Fidelity ESPP\index.xml'
System.IO.IOException: The process cannot access the file 'C:\Users\andre\OneDrive\Documents\Finance\andreva.MyMoney.Statements\Andre Fidelity ESPP\index.xml' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Walkabout.Attachments.StatementManager.SaveIndex(StatementIndex index) in C:\Users\andre\source\repos\clovett\MyMoney.Net\Source\WPF\MyMoney\Attachments\StatementManager.cs:line 306
   at Walkabout.Attachments.StatementManager.CheckFileHashes(StatementIndex index) in C:\Users\andre\source\repos\clovett\MyMoney.Net\Source\WPF\MyMoney\Attachments\StatementManager.cs:line 366
   at Walkabout.Attachments.StatementManager.LoadIndexFile(Account a) in C:\Users\andre\source\repos\clovett\MyMoney.Net\Source\WPF\MyMoney\Attachments\StatementManager.cs:line 387
Exception thrown: 'System.IO.IOException' in mscorlib.dll
Failed to load statement index 'C:\Users\andre\OneDrive\Documents\Finance\andreva.MyMoney.Statements\Andre Well Fargo IRA\index.xml'
System.IO.IOException: The process cannot access the file 'C:\Users\andre\OneDrive\Documents\Finance\andreva.MyMoney.Statements\Andre Well Fargo IRA\index.xml' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Walkabout.Attachments.StatementManager.SaveIndex(StatementIndex index) in C:\Users\andre\source\repos\clovett\MyMoney.Net\Source\WPF\MyMoney\Attachments\StatementManager.cs:line 306
   at Walkabout.Attachments.StatementManager.CheckFileHashes(StatementIndex index) in C:\Users\andre\source\repos\clovett\MyMoney.Net\Source\WPF\MyMoney\Attachments\StatementManager.cs:line 366
   at Walkabout.Attachments.StatementManager.LoadIndexFile(Account a) in C:\Users\andre\source\repos\clovett\MyMoney.Net\Source\WPF\MyMoney\Attachments\StatementManager.cs:line 387
System.Windows.Data Error: 40 : BindingExpression path error: 'Name' property not found on 'object' ''AccountSectionHeader' (HashCode=35042921)'. BindingExpression:Path=Name; DataItem='AccountSectionHeader' (HashCode=35042921); target element is 'ListBoxItem' (Name=''); target property is 'AutomationId' (type 'String')
The program '[6152] MyMoney.exe' has exited with code 0 (0x0).


From: andre vachon
Sent: August 2, 2022 9:50 PM
To: clovett/MyMoney.Net ***@***.***>; clovett/MyMoney.Net ***@***.***>
Cc: Author ***@***.***>
Subject: RE: [clovett/MyMoney.Net] !! Export does not include Security and Units (Issue #51)

I have an updated visual studio and code compiles and runs.
I just ran my binary, which loaded my data file and exited.
I saw this in the output window: and the ESPP index file has over 80 entries in it

'MyMoney.exe' (CLR v4.0.30319: MyMoney.exe): Loaded 'C:\WINDOWS\Microsoft.Net\assembly\GAC_MSIL\PresentationFramework-SystemCore\v4.0_4.0.0.0__b77a5c561934e089\PresentationFramework-SystemCore.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
System.Windows.Data Error: 40 : BindingExpression path error: 'Name' property not found on 'object' ''AccountSectionHeader' (HashCode=47633640)'. BindingExpression:Path=Name; DataItem='AccountSectionHeader' (HashCode=47633640); target element is 'ListBoxItem' (Name=''); target property is 'AutomationId' (type 'String')
Exception thrown: 'System.ServiceModel.Security.MessageSecurityException' in mscorlib.dll
BeginGetExchangeRate for CAD threw exception: The HTTP request was forbidden with client authentication scheme 'Anonymous'.
The thread 0x51d4 has exited with code 0 (0x0).
System.Windows.Data Error: 40 : BindingExpression path error: 'Name' property not found on 'object' ''AccountSectionHeader' (HashCode=32109884)'. BindingExpression:Path=Name; DataItem='AccountSectionHeader' (HashCode=32109884); target element is 'ListBoxItem' (Name=''); target property is 'AutomationId' (type 'String')
Filtered 48 items, found 0 matches in 0 ms
System.Windows.Data Error: 40 : BindingExpression path error: 'Name' property not found on 'object' ''AccountSectionHeader' (HashCode=38770251)'. BindingExpression:Path=Name; DataItem='AccountSectionHeader' (HashCode=38770251); target element is 'ListBoxItem' (Name=''); target property is 'AutomationId' (type 'String')
'MyMoney.exe' (CLR v4.0.30319: MyMoney.exe): Loaded 'Microsoft.GeneratedCode'.
Exception thrown: 'System.ArgumentNullException' in mscorlib.dll
Failed to load statement index 'C:\Users\andre\OneDrive\Documents\Finance\andreva.MyMoney.Statements\Andre Fidelity ESPP\index.xml'
System.ArgumentNullException: Value cannot be null.
Parameter name: path2
   at System.IO.Path.Combine(String path1, String path2)
   at Walkabout.Attachments.StatementManager.CheckFileHashes(StatementIndex index) in C:\Users\andre\source\repos\clovett\MyMoney.Net\Source\WPF\MyMoney\Attachments\StatementManager.cs:line 359
   at Walkabout.Attachments.StatementManager.LoadIndexFile(Account a) in C:\Users\andre\source\repos\clovett\MyMoney.Net\Source\WPF\MyMoney\Attachments\StatementManager.cs:line 387
Exception thrown: 'System.ArgumentNullException' in mscorlib.dll
Failed to load statement index 'C:\Users\andre\OneDrive\Documents\Finance\andreva.MyMoney.Statements\Andre Well Fargo IRA\index.xml'
System.ArgumentNullException: Value cannot be null.
Parameter name: path2
   at System.IO.Path.Combine(String path1, String path2)
   at Walkabout.Attachments.StatementManager.CheckFileHashes(StatementIndex index) in C:\Users\andre\source\repos\clovett\MyMoney.Net\Source\WPF\MyMoney\Attachments\StatementManager.cs:line 359
   at Walkabout.Attachments.StatementManager.LoadIndexFile(Account a) in C:\Users\andre\source\repos\clovett\MyMoney.Net\Source\WPF\MyMoney\Attachments\StatementManager.cs:line 387
The program '[21216] MyMoney.exe' has exited with code 0 (0x0).

**Comment by clovett** [comment]
thanks for the detailed stack traces.  Having no filename or hash is fine, and should not be the cause this problem.  Are you using a build from the the master branch or  the released version of the app?  Your line numbers above don't match the current sources.  

Also this error is odd:
> 'C:\Users\andre\OneDrive\Documents\Finance\andreva.MyMoney.Statements\Andre Well Fargo IRA\index.xml' because it is being used by another process.

Were you editing the index.xml file in a separate editor by any chance?

**Comment by andreva7** [comment]
I was not. But this problem no longer repros. you fixed it with a previous checkin
