### ISSUE TITLE
Exception selecting an account in the account list.

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#56]
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at Walkabout.Data.SecurityFifoQueue.<Sell>d__5.MoveNext() in C:\Users\andre\source\repos\clovett\MyMoney.Net\Source\WPF\MyMoney\Database\CostBasis.cs:line 270
   at Walkabout.Views.BrokerageAccountGraphGenerator.<Prepare>d__6.MoveNext() in C:\Users\andre\source\repos\clovett\MyMoney.Net\Source\WPF\MyMoney\Views\GraphGenerators.cs:line 272
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Walkabout.MainWindow.<>c__DisplayClass172_0.<<UpdateTransactionGraph>b__0>d.MoveNext() in C:\Users\andre\source\repos\clovett\MyMoney.Net\Source\WPF\MyMoney\MainWindow.xaml.cs:line 3040
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Walkabout.MainWindow.<UpdateTransactionGraph>d__172.MoveNext() in C:\Users\andre\source\repos\clovett\MyMoney.Net\Source\WPF\MyMoney\MainWindow.xaml.cs:line 3040
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by andreva7** [comment]
Repros every time.

View from VS:
![Exception Screenshot](https://user-images.githubusercontent.com/37969784/184464903-92d41bb1-708a-4b88-b106-dc5961c505a7.png)

**Comment by clovett** [comment]
Great bug report thanks, I pushed a fix.  Interestingly this bug has been there for a long time and is related to a "Transfer" transaction that moves stocks to a different account.  Did you recently add a new stock Transfer transaction recently?

**Comment by clovett** [comment]
This should be fixed in 2.0.0.15, let me know if you see it again, thanks.

**Comment by andreva7** [comment]
Working fine now. Thanks!

**Comment by andreva7** [comment]
I did not add any transfers.

The networth feature does not work with closed accounts, so I was going through the process of un-closing 60 old accounts one by one (we can talk about that more 😉).

This happened when I reenabled one specific account.

-Andre
