### ISSUE TITLE
Error message when running under the debugger

### ISSUE THREAD

**Issue by andreva7** [clovett/MyMoney.Net#70]
I consistently get this error message when running under the debugger when I exit mymoney.
It used to happen on another index file a while back, and that magically disappeared.
 
Failed to load statement index 'C:\Users\andre\OneDrive\Documents\Finance\andreva.MyMoney.Statements\Andre IRA Well Fargo 5408\index.xml'
System.IO.IOException: The process cannot access the file 'C:\Users\andre\OneDrive\Documents\Finance\andreva.MyMoney.Statements\Andre IRA Well Fargo 5408\index.xml' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Walkabout.Attachments.StatementManager.SaveIndex(StatementIndex index) in C:\Users\andre\source\repos\clovett\MyMoney.Net\Source\WPF\MyMoney\Attachments\StatementManager.cs:line 333
   at Walkabout.Attachments.StatementManager.CheckFileHashes(StatementIndex index) in C:\Users\andre\source\repos\clovett\MyMoney.Net\Source\WPF\MyMoney\Attachments\StatementManager.cs:line 472
   at Walkabout.Attachments.StatementManager.LoadIndexFile(Account a) in C:\Users\andre\source\repos\clovett\MyMoney.Net\Source\WPF\MyMoney\Attachments\StatementManager.cs:line 498

**Comment by clovett** [comment]
I think I found the bug, see b609ad8cf130437d0d6c792fd57d766a43d104bb

**Comment by andreva7** [comment]
Error message is gone!
